<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>fe361fdc-4910-4ad7-b756-5bd358242e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/header/div/div[3]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.menu-dekstop.css-1avegbk > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13bb4e9d-60c9-4984-aefd-9fb2edbc5249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>625601b8-60e9-46eb-a44c-28f592e76f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y6oh9p&quot;]/div[1]/div[@class=&quot;sticky&quot;]/div[@class=&quot;css-79elbk&quot;]/header[@class=&quot;css-y3081g&quot;]/div[@class=&quot;css-ujyk5r&quot;]/div[@class=&quot;css-70qvj9&quot;]/div[@class=&quot;css-1n963ky&quot;]/button[@class=&quot;menu-dekstop css-1avegbk&quot;]/span[1]</value>
      <webElementGuid>0657ed52-509a-4fa4-9453-6edd51c5bc3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/header/div/div[3]/div/button/span</value>
      <webElementGuid>86dfd287-f07c-456e-bfc6-00898f616963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::span[1]</value>
      <webElementGuid>1a656b6e-dda4-4a7f-b603-418d6fc73db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Product'])[1]/following::span[3]</value>
      <webElementGuid>d22da116-ef5d-4c94-992c-63c6fc5eff7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eProcurement'])[1]/preceding::span[1]</value>
      <webElementGuid>02ede57b-6549-4e53-b978-7f9839ce5263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo Bank'])[1]/preceding::span[1]</value>
      <webElementGuid>b0a5b505-e6d8-4b09-bb4d-78306fe52e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>85bf3106-650d-4df6-becb-1035078f5465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span</value>
      <webElementGuid>905dc001-1a68-46a7-9c94-0a464fe43716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>1ba8f365-7e2f-431e-a9a5-662803801007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
