<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>block.txt</name>
   <tag></tag>
   <elementGuidId>69443f81-7147-4f29-a5db-ec9c165a954d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-cancel-button</value>
      <webElementGuid>bd4b9a91-aa70-449a-bc15-a010f3f8aa48</webElementGuid>
   </webElementProperties>
</WebElementEntity>
